### ISSUE TITLE
mpv not found on fedora linux

### ISSUE THREAD

**Issue by wolf-coder** [media-kit/media-kit#594]
- Running the demo code results in an error:

```
CMake Error at flutter/ephemeral/.plugin_symlinks/media_kit_video/linux/CMakeLists.txt:16 (add_library):
  Target "media_kit_video_plugin" links to target "PkgConfig::mpv" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?
```

- The required packages were properly  installed ( `yum install mpv  mpv-libs-devel)`
- What am I missing here?

**Comment by alexmercerind** [comment]
Feel free to share any workarounds/details you find. We don't provide binaries for GNU/Linux, because packages from distribution are used, which is responsibility of developers or users.

**Comment by wolf-coder** [comment]
Can I have  guidance on resolving this issue. Could you please provide details on any specific modifications to the building process or additional steps that might be necessary to ensure the correct dependencies are detected during the build?

**Comment by alexmercerind** [comment]
I don't know unfortunately; never used Fedora.

**Comment by alexmercerind** [comment]
Also: #595.

**Comment by Velosofy** [comment]
Have you install `mpv-libs` ? not `mpv-libs-devel`

**Comment by zyrouge** [comment]
> Have you install `mpv-libs` ? not `mpv-libs-devel`

I'm on Fedora and only installed `mpv` and `mpv-devel`. Afaik, `mpv-libs` was pulled by `mpv-devel` as a dependency.

**Comment by andrey-utkin** [comment]
On Fedora, the package needed is `mpv-devel`. It has pkg-config file `/usr/lib64/pkgconfig/mpv.pc`, and pkg-config util can find it, but cmake somehow can't. My workaround is to specify PKG_CONFIG_PATH.

```sh
export PKG_CONFIG_PATH=/usr/lib64/pkgconfig; flutter build linux
```

**Comment by wolf-coder** [comment]
@andrey-utkin 
Which fedora version are you using?

**Comment by andrey-utkin** [comment]
I'm on Fedora 37.

**Comment by JGNS** [comment]
The same problem occurs on embedded devices. Does anyone have such experience? I have no way to use flutter to play videos in embedded linux.  #638

**Comment by fabioselau077** [comment]
> The same problem occurs on embedded devices. Does anyone have such experience? I have no way to use flutter to play videos in embedded linux. #638

resolved? same here in in Ubuntu

**Comment by hauserx** [comment]
@fabioselau077 For Ubuntu you need `sudo apt install libmpv-dev mpv` as described on:
https://github.com/media-kit/media-kit?tab=readme-ov-file#ubuntudebian

Later you may also face `collect2: error: ld returned 1 exit status` issue with solution described here (install media-kit manually instead of snap + install libstdc++-12-dev): https://github.com/media-kit/media-kit/issues/550

**Comment by JGNS** [comment]
> @fabioselau077 For Ubuntu you need `sudo apt install libmpv-dev mpv` as described on: https://github.com/media-kit/media-kit?tab=readme-ov-file#ubuntudebian
> 
> Later you may also face `collect2: error: ld returned 1 exit status` issue with solution described here (install media-kit manually instead of snap + install libstdc++-12-dev): #550

I know this instruction, I have executed it。The special thing is that my ubuntu is not desktop ubuntu, but runs on an embedded device。see: #638 ,can you help me,thans

**Comment by VShaikh** [comment]
I am using Fedora 40, are below installations sufficient ?
sudo dnf install mpv-devel-0.37.0-4.fc40.x86_64
sudo dnf install mpv-libs-0.37.0-4.fc40.i686
sudo dnf install mpv-0.37.0-4.fc40.x86_64

**Comment by hansyulian** [comment]
hi, i'm on raspberry pi os and i got the same issue. anyone have any idea? i already do the `sudo apt install libmpv1 libmpv-dev` and still have the issue
